---
services:
  traefik:
    image: registry.gitlab.com/naturalis/lib/docker/traefik:v3.6
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
      - backend
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "127.0.0.1:8079:8080"
    environment:
      - TRANSIP_ACCOUNT_NAME
      - TRANSIP_PRIVATE_KEY_PATH=/etc/traefik/transip.key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/transip.key:/etc/traefik/transip.key:ro
      - ./letsencrypt:/letsencrypt

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2.2.0
    restart: unless-stopped
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET
      - SECRET
      - AUTH_HOST
      - COOKIE_DOMAIN
      - WHITELIST
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-forward-auth.rule=Host(`${OAUTH_FQDN}`)"
      - "traefik.http.routers.traefik-forward-auth.tls=true"
      - "traefik.http.routers.traefik-forward-auth.tls.certresolver=transipresolver"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - web

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    restart: unless-stopped
    ports:
      # - "9000:9000" # ative clickhouse client
      - "8123:8123" # for HTML client
    networks:
      - backend
    volumes:
      #- clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/etc/clickhouse-server/config.d/named_collections.xml:/etc/clickhouse-server/config.d/named_collections.xml
      - ./clickhouse/scripts:/var/lib/clickhouse/user_files
      - ./clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      # - ./clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  postgres:
    build: ./postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - WEBDAV_ENDPOINT_URL
      - WEBDAV_USER
      - WEBDAV_PASSWORD
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - lawa_data:/var/lib/postgresql/lawa
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d/${POSTGRES_CONFD:-default}:/conf.d
      - ./postgres/scripts:/var/lib/postgresql/scripts

  app:
    build:
      context: ./app
    restart: unless-stopped
    networks:
      # - web
      - backend
    ports:
      - "8050:8050"
    volumes:
      - lawa_data:/app/assets/images/
    environment:
      - CLICKHOUSE_HOST
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
      - CLICKHOUSE_DB
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - WEBDAV_ENDPOINT_URL
      - WEBDAV_USER
      - WEBDAV_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${LAWA_FQDN}`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=transipresolver"
      - "traefik.http.routers.app.middlewares=traefik-forward-auth@docker"
      - "traefik.http.services.app.loadbalancer.server.port=8050"

volumes:
  lawa_data:
#   clickhouse_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /data/clickhouse
#   postgres_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /data/postgres

networks:
  web:
    internal: false
  backend:
    internal: false
...

