---
- name: Determine network units to override
  ansible.builtin.find:
    paths: /run/systemd/network/
    patterns: '*.network'
    file_type: file
  register: network_units

- name: Assert network unit override dir
  ansible.builtin.file:
    path: "/etc/systemd/network/{{ unit.path | basename }}.d"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ network_units.files }}"
  loop_control:
    loop_var: unit

- name: Ignore DNS from DHCP on all network units
  ansible.builtin.copy:
    src: files/dns.conf
    dest: "/etc/systemd/network/{{ unit.path | basename }}.d/dns.conf"
    mode: '0644'
    owner: root
    group: root
  loop: "{{ network_units.files }}"
  loop_control:
    loop_var: unit
  notify: reconfig_dns

- name: Assert systemd-resolved override dir
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install override on systemd-resolved config
  ansible.builtin.template:
    src: resolved.conf.d-dns.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns.conf
    mode: '0644'
    owner: root
    group: root
  notify: daemon-reload
...
