---
- name: Assert service dir
  ansible.builtin.file:
    path: /etc/systemd/system/systemd-networkd-wait-online.service.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Install override on systemd-networkd-wait-online.service
  ansible.builtin.copy:
    src: files/systemd-networkd-wait-online.service.d-override.conf
    dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/override.conf
    mode: '0644'
    owner: root
    group: root
  notify: daemon-reload
...
