---
- name: Install unattended updates
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Config 20auto-upgrades
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Config 50unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'

- name: Add maintenance reboot script
  ansible.builtin.copy:
    src: files/maintenance.sh
    dest: /usr/local/sbin/maintenance.sh
    mode: '0700'

- name: Create maintenance reboot service
  ansible.builtin.template:
    src: templates/maintenance-reboot.service.j2
    dest: /etc/systemd/system/maintenance-reboot.service
    owner: root
    group: root
    mode: '0644'
  notify: start_maintenance_timer

- name: Create maintenance reboot timer
  ansible.builtin.template:
    src: templates/maintenance-reboot.timer.j2
    dest: /etc/systemd/system/maintenance-reboot.timer
    owner: root
    group: root
    mode: '0644'
  notify: start_maintenance_timer
  register: maintenance_timer

- name: Enable and start maintenance reboot timer  # noqa no-handler
  ansible.builtin.systemd:
    name: maintenance-reboot.timer
    enabled: true
    state: started
  when: not maintenance_timer.changed
