---
- name: Lawa instances
  hosts: lawa_prd
  gather_facts: true
  become: true
  vars_prompt:
    # App
    - name: "webdav_endpoint_url"
      prompt: "webdav_endpoint_url"
      private: false

    - name: "webdav_user"
      prompt: "webdav_user"
      private: false

    - name: "webdav_password"
      prompt: "webdav_password"
      private: false

    # ClickHouse
    - name: "clickhouse_password"
      prompt: "clickhouse_password"
      private: false

    # Postgres
    - name: "postgres_password"
      prompt: "postgres_password"
      private: false

    # Oauth
    - name: "providers_google_client_id"
      prompt: "providers_google_client_id"
      private: false

    - name: "providers_google_client_secret"
      prompt: "providers_google_client_secret"
      private: false

    - name: "secret"
      prompt: "secret"
      private: false

    - name: "auth_host"
      prompt: "auth_host"
      private: false

    - name: "cookie_domain"
      prompt: "cookie_domain"
      private: false

    - name: "whitelist"
      prompt: "whitelist"
      private: false

    - name: "oauth_fqdn"
      prompt: "oauth_fqdn"
      private: false

    # Traefik
    - name: "email"
      prompt: "email"
      private: false

    - name: "lawa_fqdn"
      prompt: "lawa_fqdn"
      private: false

    - name: "transip_account_name"
      prompt: "transip_account_name"
      private: false

    - name: "transip_key"
      prompt: "transip_key"
      private: false

  tasks:
    - name: Gather facts
      ansible.builtin.setup:
      tags: gather_facts

    # - name: Create folders to hold data volumes
    #   ansible.builtin.file:
    #     path: "{{ item }}"
    #     state: directory
    #     mode: "0755"
    #   loop:
    #     - /data/clickhouse
    #     - /data/postgres

    - name: Install and manage docker
      ansible.builtin.import_role:
        name: docker
      tags: docker
...

